spring.application.name=pricing_system

spring.datasource.url=jdbc:postgresql://dpg-d6of9i15pdvs73ehvh2g-a.oregon-postgres.render.com:5432/demorender_znt7?sslmode=require
spring.datasource.username=demorender_znt7_user
spring.datasource.password=K7nKAAHRvxAAfEOALwDYqvO6jh1Yf9Oq

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
